!INTERFILE  :=
!imaging modality := PT
name of data file := ../sinogram/michelogram.s
originating system := Userdefined
!version of keys := STIR3.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := signed integer
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 7
matrix axis label [3] := axial coordinate
!matrix size [3] := {77,69,69,55,55,41,41}
matrix axis label [2] := view
!matrix size [2] := 312
matrix axis label [1] := tangential coordinate
!matrix size [1] := 624
minimum ring difference per segment := { -3,-10,4,-17,11,-24,18}
maximum ring difference per segment := { 3,-4,10,-11,17,-18,24}
Scanner parameters:= 
Scanner type := Userdefined
Number of rings                          := 39
Number of detectors per ring             := 624
Inner ring diameter (cm)                 := 82.4
Average depth of interaction (cm)        := 1
Distance between rings (cm)              := 0.41
Default bin size (cm)                    := 0.205
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 0
Default number of arc-corrected bins     := 0
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 3
Number of crystals per block in axial direction             := 13
Number of crystals per block in transaxial direction        := 13
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 13
Number of crystals per singles unit in transaxial direction := 13
end scanner parameters:=
effective central bin size (cm) := 0.205
number of time frames := 1
!END OF INTERFILE :=
