#=====================================================
# VISUALISATION
#=====================================================

#/vis/disable
/vis/open                           OGLSX
/vis/viewer/set/viewpointThetaPhi   0 0
/vis/viewer/zoom                    30.0
/vis/drawVolume
/tracking/storeTrajectory           1
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction         accumulate

/gate/geometry/setMaterialDatabase    GateMaterials.db